### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by AntonisTerzo**
In this pr i added a logo for the site. #19 
Capture1

### CODE REVIEW

**Comment by MickeMarten** [comment]
Looks good!
The html-element "header__div" will be removied with my latest pr.

**Comment by oskber** [comment]
Looks good!

**Comment by MadeleineDahlqvist** [comment]
Looks good!

**Review by ANschoolacc — APPROVED** [review]
The logo looks good. Much better when adding more margin on the left! 
It seems like you have some conflicts to resolve but when that is fixed i say you should merge the changes.

**Pull request merged**
