### PR TITLE
Added opening hours

### PR DESCRIPTION
**Pull request by ANschoolacc**
Added section in aboutUs page that displays opening hours. Also added styling to that section and some styling to aboutUs main element.

Here is a caption of what i have added. Please tell me if you have any suggestions for changes to the newly added content.

image

### CODE REVIEW

**Comment by MadeleineDahlqvist** [comment]
I think it looks good for now since @ConnyPettersson is going to add more content.
Good job!

**Comment by ConnyPettersson** [comment]
Looks good!

**Review by AntonisTerzo — COMMENTED** [review]
Looks good only a confict in main.css and the we can merge it.

**Comment by oskber** [comment]
Looks good! Only thing you could fix is the typo in the title "Öppetider", should be "Öppettider" :)

Some conflicts appeared but should be an easy fix

**Review by ConnyPettersson — COMMENTED** [review]
Looks good!

**Comment by ANschoolacc** [comment]
Fixed the typo and merge conflict. Will now merge.

**Pull request merged**
