### PR TITLE
Header nav

### PR DESCRIPTION
**Pull request by MickeMarten**
Added navbar and ul with links to all html.pages.
Added css for header, nav and ul-items.
Added "images" properties to json.file.
Changed source from main.css to /main.css in aboutus.html and movies-html.

Skärmklipp

### CODE REVIEW

**Review by oskber — COMMENTED** [review]
Looks good, only some conflicts that needs to be solved. 
And we should add 'Roboto' as font-family to all html

**Comment by MadeleineDahlqvist** [comment]
Looks good!

**Review by ANschoolacc — COMMENTED** [review]
Nice job! The header looks really good.

Only thing i thought about was that you don't have classes for the ul and li elements. When using the BEM method you are supposed to give all elements that are called upon in css a classname. When not called upon you don't have to. 

Just a small detail though, i think that the css overall looks well organized and understandable.

**Comment by ConnyPettersson** [comment]
Looks nice!

**Comment by AntonisTerzo** [comment]
Everything Looks good! Only some small issues that the guys discovered 😁

**Pull request merged**
